@param String selectedMenu
@param String p1Url
@param String p2Url

@template.fragments.s03d04mpalayout(
  content = @`
    <%-- docs:start page --%>
    <div class="is-flex is-justify-content-space-around p-1">
        <div class="p-1">
            <h4 class="subtitle is-4">Page 2</h4>
        </div>
    </div>
    <%-- docs:end page --%>
`,
  selectedMenu = selectedMenu,
  p1Url = p1Url,
  p2Url = p2Url
)
